name: Test passage CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  run-tests:
    name: Run Cargo Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Enable Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build executables with features
        run: |
          cargo build --bin server --features="server-deps"
          cargo build --bin client --features="client-deps"

      - name: Run tests
        run: cargo test --workspace --all-targets --features="server-deps,client-deps"
